# Site settings
title: MA001 - Basic Algebra
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Basic description for MA001.
baseurl: "course_ma001" # the subpath of your site, e.g. /blog/
url: "https://saylordotorg.github.io" # the base hostname & protocol for your site
twitter_username: saylordotorg
github_username:  saylordotorg

# Build settings
markdown: kramdown
permalink: /:title/


